name: Deploy to Firebase
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci

      - name: Lint Checks
        run: npm run lint && npm run prettier && npm run stylelint

      - name: Unit Tests
        run: npm run test:coverage

      - name: Build
        run: npm run build

      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_THE_USHA_GUPTA }}'
          channelId: live
          projectId: the-usha-gupta